apiVersion: v1
kind: Service
metadata:
  name: hota-org-uk-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: hota-org-uk-service
