replicaCount: 1
image:
  repository: ghcr.io/houses-on-the-air/hota.org.uk
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: hota.org.uk
      paths: /
  tls:
    - secretName: hota-org-uk-tls
      hosts:
        - hota.org.uk
secret:
  tlsCert: "" # work out where to save these
  tlsKey: "" # base64 encode
