name: Generate SBOM

on:
    schedule:
        - cron: 0 0 * * * # Runs daily at midnight UTC
    push:
    workflow_dispatch:

jobs:
    generate-sbom:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '14'

          - name: Install CycloneDX CLI
            run: npm install -g @cyclonedx/cyclonedx-npm

          - name: Generate SBOM
            run: cyclonedx-npm --output bom.xml

          - name: Upload SBOM artifact
            uses: actions/upload-artifact@v4
            with:
              name: sbom
              path: bom.xml
